const createUnits = [
  {
    unitName: "Gorjačar",
    costWood: 100,
    costClay: 100,
    costIron: 100,
    costWheat: 100,
    timeToBuild: 10,
    attack: 10,
    defense: 1,
    type: "infantry",
    upkeep: 1,
    unitIcon: "https://cdn-icons-png.flaticon.com/512/3903/3903967.png",
    unitBuilding: "barracks",
  },
  {
    unitName: "Suličar",
    costWood: 200,
    costClay: 200,
    costIron: 200,
    costWheat: 200,
    timeToBuild: 20,
    attack: 5,
    defense: 15,
    type: "infantry",
    upkeep: 2,
    unitIcon: "https://cdn-icons-png.flaticon.com/512/1083/1083291.png",
    unitBuilding: "barracks",
  },
  {
    unitName: "Long Bowman",
    costWood: 200,
    costClay: 200,
    costIron: 200,
    costWheat: 200,
    timeToBuild: 20,
    attack: 15,
    defense: 5,
    type: "archer",
    upkeep: 2,
    unitIcon: "https://img.lovepik.com/element/45004/4336.png_860.png",
    unitBuilding: "barracks",
  },
  {
    unitName: "Crossbow",
    costWood: 500,
    costClay: 500,
    costIron: 500,
    costWheat: 500,
    timeToBuild: 40,
    attack: 25,
    defense: 10,
    type: "archer",
    upkeep: 3,
    unitIcon:
      "https://d1nhio0ox7pgb.cloudfront.net/_img/g_collection_png/standard/512x512/crossbow.png",
    unitBuilding: "barracks",
  },

  {
    unitName: "Jadn konj",
    costWood: 50,
    costClay: 50,
    costIron: 50,
    costWheat: 50,
    timeToBuild: 10,
    attack: 10,
    defense: 5,
    type: "cavalry",
    upkeep: 2,
    unitIcon: "https://cdn-icons-png.flaticon.com/512/2432/2432306.png",
    unitBuilding: "stables",
  },

  {
    unitName: "Tevtonski vitez",
    costWood: 100,
    costClay: 100,
    costIron: 100,
    costWheat: 100,
    timeToBuild: 10,
    attack: 40,
    defense: 20,
    type: "cavalry",
    upkeep: 10,
    unitIcon:
      "https://e7.pngegg.com/pngimages/251/218/png-clipart-crusades-middle-ages-knight-computer-icons-knight-horse-logo.png",
    unitBuilding: "stables",
  },
  {
    unitName: "Paladin",
    costWood: 200,
    costClay: 200,
    costIron: 200,
    costWheat: 200,
    timeToBuild: 20,
    attack: 15,
    defense: 40,
    type: "cavalry",
    upkeep: 5,
    unitIcon:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxXvQPqJkDM_PU6J13KiwhsEaAQHxMHk9Y2Q&usqp=CAU",
    unitBuilding: "stables",
  },
]; //END ARRAY

export {createUnits};
